<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Woodzone Services Gutenverse Appointment', 'woodzone' ),
	'categories' => array( 'woodzone-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-YCTrEI","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":737,"image":"https://designer.gutenverse.com/woodzone/wp-content/uploads/sites/89/2024/11/manual-work.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"fixed":{"Desktop":true}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-0"}},"opacity":"0.7","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}}} -->
<div class="section-wrapper" data-id="YCTrEI"><section class="wp-block-gutenverse-section guten-element guten-section guten-YCTrEI layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-REsfK5","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-REsfK5"><div class="guten-column-wrapper" data-id="REsfK5"><!-- wp:gutenverse/form-builder {"elementId":"guten-tC35cL","formId":{"label":"Form Reservation Woodzone","value":717},"successPadding":{"Desktop":[]},"successMargin":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"successBorderResponsive":{"Desktop":{"radius":[]}},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"30","bottom":"50","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-tC35cL animated guten-element-hide desktop-fadeInLeft" data-form-id="717"><!-- wp:gutenverse/form-input-text {"elementId":"guten-0eaM1U","showLabel":false,"inputPlaceholder":"Your  Name","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"color":{"r":0,"g":0,"b":0,"a":0.1},"width":1,"type":"solid"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-0eaM1U hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your  Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/section {"width":{"Desktop":""},"isChild":true,"gap":"no","elementId":"guten-atEvr2","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"30","left":"0"}}}} -->
<div class="section-wrapper" data-id="atEvr2"><section class="wp-block-gutenverse-section guten-element guten-section guten-atEvr2 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-gbtEz5","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-gbtEz5"><div class="guten-column-wrapper" data-id="gbtEz5"><!-- wp:gutenverse/form-input-text {"elementId":"guten-Jaudxd","showLabel":false,"inputPlaceholder":"Your Phone","inputName":"input-text-phone","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"%","point":""}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"color":{"r":0,"g":0,"b":0,"a":0.1},"width":1,"type":"solid"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-Jaudxd hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Phone" name="input-text-phone" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-MbNK3h","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MbNK3h"><div class="guten-column-wrapper" data-id="MbNK3h"><!-- wp:gutenverse/form-input-email {"elementId":"guten-MR61G4","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"%","point":""}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"width":1,"type":"solid","color":{"r":0,"g":0,"b":0,"a":0.1}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-MR61G4 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-select {"elementId":"guten-l7YC34","showLabel":false,"inputPlaceholder":"Select Services","showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"labelMargin":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"selectOptions":[{"value":"1","label":"Wooden Furniture","_key":"lsBK5w"},{"value":"2","label":"Home Renovation","_key":"gGnzX0"},{"value":"3","label":"Windows \u0026 Shutters","_key":"Jfn60E"},{"value":"4","label":"Wooden Floor","_key":"WDFuIq"},{"value":"5","label":"Custom Work","_key":"HUIuze"},{"value":"6","label":"Finish Carpentry","_key":"mZMEZ9"}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"25","left":"25","top":"15","bottom":"15"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":1,"type":"solid","color":{"r":0,"g":0,"b":0,"a":0.1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-l7YC34 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="input-select" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Select Services</option><option value="1">Wooden Furniture</option><option value="2">Home Renovation</option><option value="3">Windows &amp; Shutters</option><option value="4">Wooden Floor</option><option value="5">Custom Work</option><option value="6">Finish Carpentry</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-uxCo8d","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"35","left":"0"}}},"inputHeight":{"Desktop":"140"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"25","left":"25","top":"15","bottom":"15"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.1}}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-uxCo8d hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/button {"elementId":"guten-rdWbUl","content":"Make Appointment","alignButton":{"Mobile":"left","Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-1"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"color":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"PFoznL","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"600","transform":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1"}}}} -->
<div class="guten-element guten-button-wrapper guten-rdWbUl"><a class="guten-button guten-button-sm" href="#"><span>Make Appointment</span></a></div>
<!-- /wp:gutenverse/button --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-CY5x5H","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"80"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CY5x5H"><div class="guten-column-wrapper" data-id="CY5x5H"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-66Y2Wg","text":"","focusText":"Make Appointment","subText":"Needs Experience Carpenter Service? Book Now","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"mainPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"3KyvQK","font":{"label":"Lato","value":"Lato","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":""}},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"focusPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"subColor":{"type":"variable","id":"theme-5"},"subTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-advanced-heading guten-66Y2Wg"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Make Appointment</span></h2></div><span class="heading-subtitle">Needs Experience Carpenter Service? Book Now</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-1y76io","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element gutenverse-text-editor guten-1y76io"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius tempor incididunt ut labore et dolore magna aliqua. Ut enim adiqua minim veniam quis nostrud exercitation ullamco</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":""},"isChild":true,"gap":"no","elementId":"guten-H23LKM","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="H23LKM"><section class="wp-block-gutenverse-section guten-element guten-section guten-H23LKM layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-20YivR","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-20YivR"><div class="guten-column-wrapper" data-id="20YivR"><!-- wp:gutenverse/heading {"elementId":"guten-l2laMA","type":4,"color":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"BL8phF","font":{"label":"Lato","value":"Lato","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-l2laMA">Denpasar, Bali</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-1ToUUk","spaceBetween":{"Desktop":"15"},"iconColor":{"type":"variable","id":"theme-3"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-1ToUUk"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-HeKlxX"} -->
<div class="guten-element guten-icon-list-item guten-HeKlxX"><a id="guten-HeKlxX"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Puputan No 142, Sumerta Kelod, Bali - 80234</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-PDtp5e"} -->
<div class="guten-element guten-icon-list-item guten-PDtp5e"><a id="guten-PDtp5e"><i class="far fa-envelope"></i><span class="list-text ">support@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-bFHBon"} -->
<div class="guten-element guten-icon-list-item guten-bFHBon"><a id="guten-bFHBon"><i class="fas fa-phone"></i><span class="list-text ">(+021) 231 - 3326</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-WBsreq"} -->
<div class="guten-element guten-icon-list-item guten-WBsreq"><a id="guten-WBsreq"><i class="fas fa-clock"></i><span class="list-text ">Mon-Fri 08:00 - 17:00</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-SWiW2A","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SWiW2A"><div class="guten-column-wrapper" data-id="SWiW2A"><!-- wp:gutenverse/heading {"elementId":"guten-zbsAzJ","type":4,"color":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"BL8phF","font":{"label":"Lato","value":"Lato","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-zbsAzJ">Canggu, Bali</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-JwMKHO","spaceBetween":{"Desktop":"15"},"iconColor":{"type":"variable","id":"theme-3"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-JwMKHO"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-EOf2La"} -->
<div class="guten-element guten-icon-list-item guten-EOf2La"><a id="guten-EOf2La"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Canggu No 511, Badung Reg, Bali - 80234</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-OZppDB"} -->
<div class="guten-element guten-icon-list-item guten-OZppDB"><a id="guten-OZppDB"><i class="far fa-envelope"></i><span class="list-text ">support@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-DzQRff"} -->
<div class="guten-element guten-icon-list-item guten-DzQRff"><a id="guten-DzQRff"><i class="fas fa-phone"></i><span class="list-text ">(+021) 231 - 3326</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-JOoQVO"} -->
<div class="guten-element guten-icon-list-item guten-JOoQVO"><a id="guten-JOoQVO"><i class="fas fa-clock"></i><span class="list-text ">Mon-Fri 08:00 - 17:00</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"manual-work.webp","image_url":"https:\/\/designer.gutenverse.com\/woodzone\/wp-content\/uploads\/sites\/89\/2024\/11\/manual-work.webp","type":"sync","id":1311}]',
	'is_sync' => true,
);
