<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Woodzone Services Gutenverse FAQ', 'woodzone' ),
	'categories' => array( 'woodzone-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-P4PQth","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}}} -->
<div class="section-wrapper" data-id="P4PQth"><section class="wp-block-gutenverse-section guten-element guten-section guten-P4PQth layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-X9XLcM","horizontalAlign":{"Desktop":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-X9XLcM"><div class="guten-column-wrapper" data-id="X9XLcM"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-qU9DpU","alignText":{"Desktop":"center"},"text":"","focusText":"FAQ","subText":"Popular Question","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"3KyvQK","font":{"label":"Lato","value":"Lato","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":""}},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-advanced-heading guten-qU9DpU"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">FAQ</span></h2></div><span class="heading-subtitle">Popular Question</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Mo7pGj","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"520","unit":"px"},"Tablet":{"point":"520","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-Mo7pGj"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-xVwqj2","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="xVwqj2"><section class="wp-block-gutenverse-section guten-element guten-section guten-xVwqj2 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-1cbO7N","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1cbO7N"><div class="guten-column-wrapper" data-id="1cbO7N"><!-- wp:gutenverse/accordions {"elementId":"guten-XjURKY","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right","iconColor":{"type":"variable","id":"theme-3"},"iconActiveColor":{"type":"variable","id":"theme-5"},"titleBackgroundColor":{"type":"variable","id":"theme-5"},"titleTextColor":{"type":"variable","id":"theme-0"},"titleActiveColor":{"type":"variable","id":"theme-5"},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"25","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"40"}}},"contentTextColor":{"type":"variable","id":"theme-2"},"contentTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"40","bottom":"40","left":"40"}}},"accordionBorder":{"radius":{"Desktop":[]},"all":{"type":"none","width":null},"bottom":{"type":"none"}},"accordionBorderResponsive":{"Tablet":{"radius":[]}},"titleBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"titleBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"contentBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"border":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"25","left":"0"}},"Tablet":[]},"titleBackgroundActiveColor":{"type":"variable","id":"theme-3"},"titleBorderActive":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"accordionBoxShadow":{"color":{"r":0,"g":0,"b":0,"a":0.1},"horizontal":"0","vertical":"3","blur":"15","spread":"0","position":"outline"},"iconMargin":{"Desktop":[],"Tablet":[]},"iconPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconActiveBorder":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-accordions guten-XjURKY"><!-- wp:gutenverse/accordion {"elementId":"guten-FIrE4W","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-FIrE4W"><div class="accordion-heading"><span class="accordion-text">What is benefit for handmade furniture?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-7vOn3T","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-7vOn3T"><div class="accordion-heading"><span class="accordion-text">What are the factors affecting the cost?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-LjqMm9","first":true,"iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-LjqMm9 active"><div class="accordion-heading"><span class="accordion-text">Can we make outdoor furniture in hardwood?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-vn7BTd","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vn7BTd"><div class="guten-column-wrapper" data-id="vn7BTd"><!-- wp:gutenverse/accordions {"elementId":"guten-budjO0","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right","iconColor":{"type":"variable","id":"theme-3"},"iconActiveColor":{"type":"variable","id":"theme-5"},"titleBackgroundColor":{"type":"variable","id":"theme-5"},"titleTextColor":{"type":"variable","id":"theme-0"},"titleActiveColor":{"type":"variable","id":"theme-5"},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"25","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"40"}}},"contentTextColor":{"type":"variable","id":"theme-2"},"contentTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"40","bottom":"40","left":"40"}}},"accordionBorder":{"radius":{"Desktop":[]},"all":{"type":"none","width":null},"bottom":{"type":"none"}},"titleBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"titleBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"contentBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"border":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"25","left":"0"}}},"titleBackgroundActiveColor":{"type":"variable","id":"theme-3"},"titleBorderActive":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"accordionBoxShadow":{"color":{"r":0,"g":0,"b":0,"a":0.1},"horizontal":"0","vertical":"3","blur":"15","spread":"0","position":"outline"},"iconMargin":{"Desktop":[],"Tablet":[]},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"iconBorder":{"radius":{"Desktop":[]},"all":{"type":"none"},"bottom":{"type":"none"}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconActiveBorder":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-accordions guten-budjO0"><!-- wp:gutenverse/accordion {"elementId":"guten-fjjC2l","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-fjjC2l"><div class="accordion-heading"><span class="accordion-text">What is benefit for handmade furniture?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-pSHfvP","iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-pSHfvP"><div class="accordion-heading"><span class="accordion-text">What are the factors affecting the cost?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion -->

<!-- wp:gutenverse/accordion {"elementId":"guten-Fdt2EH","first":true,"iconOpen":"gtn gtn-chevron-up-light","iconClosed":"gtn gtn-chevron-down-light","iconPosition":"right"} -->
<div class="accordion-item guten-Fdt2EH active"><div class="accordion-heading"><span class="accordion-text">Can we make outdoor furniture in hardwood?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="gtn gtn-chevron-up-light"></i></span><span class="accordion-icon-closed"><i class="gtn gtn-chevron-down-light"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:gutenverse/accordion --></div>
<!-- /wp:gutenverse/accordions --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => true,
);
