<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Woodzone About Gutenverse CTA Funfact', 'woodzone' ),
	'categories' => array( 'woodzone-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-KlnwGr","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":541,"image":"https://designer.gutenverse.com/woodzone/wp-content/uploads/sites/89/2024/11/roof-construction.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-0"}},"opacity":"0.7","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"160","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"180","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"20","bottom":"100","left":"20"}}}} -->
<div class="section-wrapper" data-id="KlnwGr"><section class="wp-block-gutenverse-section guten-element guten-section guten-KlnwGr layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-DmBRaG","margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DmBRaG"><div class="guten-column-wrapper" data-id="DmBRaG"><!-- wp:gutenverse/heading {"elementId":"guten-h6TwuO","textAlign":{"Mobile":"left"},"color":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"340","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-h6TwuO animated guten-element-hide desktop-fadeInLeft">Custom Woodwork With Us</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kPqs0p","alignment":{"Mobile":"left"},"textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"550","unit":"px"},"Tablet":{"point":"360","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-kPqs0p"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-pX9FYZ","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pX9FYZ"><div class="guten-column-wrapper" data-id="pX9FYZ"><!-- wp:gutenverse/buttons {"elementId":"guten-0lRSsP","alignButtons":{"Desktop":null},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-buttons horizontal guten-0lRSsP"><!-- wp:gutenverse/button {"elementId":"guten-X9YCYZ","content":"Request Consultation","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"r":124,"g":73,"b":17,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"type":"variable","id":"PFoznL","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"600","transform":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"positioningType":{"Desktop":"full"}} -->
<div class="guten-element guten-button-wrapper guten-X9YCYZ"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Request Consultation</span></a></div>
<!-- /wp:gutenverse/button -->

<!-- wp:gutenverse/button {"elementId":"guten-RgJZcD","content":"View Projects","buttonHeight":{"Desktop":"0"},"alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"11"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"type":"variable","id":"AKa8BT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"hoverIconColor":{"type":"variable","id":"theme-1"},"hoverTextColor":{"type":"variable","id":"theme-1"},"positioningType":{"Desktop":"full"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-button-wrapper guten-RgJZcD"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>View Projects</span><i class="fa-lg gtn gtn-right-arrow-light"></i></a></div>
<!-- /wp:gutenverse/button --></div>
<!-- /wp:gutenverse/buttons --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-nhPIw0","border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="nhPIw0"><section class="wp-block-gutenverse-section guten-element guten-section guten-nhPIw0 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-46CJEC"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-46CJEC"><div class="guten-column-wrapper" data-id="46CJEC"><!-- wp:gutenverse/section {"width":{"Desktop":""},"isChild":true,"gap":"no","elementId":"guten-cqsKAE","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":[]}},"boxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","position":"outline","color":{"r":0,"g":0,"b":0,"a":0.08}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-100","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-110","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"-50","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}},"Mobile":[]},"zIndex":{"Desktop":2},"animation":{"type":{"Desktop":"slideInUp"},"duration":"normal"}} -->
<div class="section-wrapper" data-id="cqsKAE"><section class="wp-block-gutenverse-section guten-element guten-section guten-cqsKAE animated guten-element-hide desktop-slideInUp layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-99scHF","margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-99scHF"><div class="guten-column-wrapper" data-id="99scHF"><!-- wp:gutenverse/fun-fact {"elementId":"guten-3eXMs6","icon":"gtn gtn-drill-light","iconColor":{"Desktop":{"type":"variable","id":"theme-3"}},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"prefix":"","number":"4,452","suffix":"","title":"Successful Projects","showSupper":true,"superColor":{"type":"variable","id":"theme-1"},"superTypography":{"type":"variable","id":"gVRepE","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"superTop":{"Desktop":"9"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"r":37,"g":36,"b":37,"a":1}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":"0"},"numberRightSpace":{"Desktop":"0"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-3eXMs6 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-drill-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="4,452" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Successful Projects</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-bZaIoD","margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bZaIoD"><div class="guten-column-wrapper" data-id="bZaIoD"><!-- wp:gutenverse/fun-fact {"elementId":"guten-s3f6uA","icon":"gtn gtn-team-1-light","iconColor":{"Desktop":{"type":"variable","id":"theme-3"}},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"prefix":"","number":"2,820","suffix":"","title":"Satisfied Clients","showSupper":true,"superColor":{"type":"variable","id":"theme-1"},"superTypography":{"type":"variable","id":"gVRepE","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"superTop":{"Desktop":"9"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"r":37,"g":36,"b":37,"a":1}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":"0"},"numberRightSpace":{"Desktop":"0"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-s3f6uA guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-1-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="2,820" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Satisfied Clients</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-sFQbgW","margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sFQbgW"><div class="guten-column-wrapper" data-id="sFQbgW"><!-- wp:gutenverse/fun-fact {"elementId":"guten-QFmYhS","icon":"gtn gtn-badge","iconColor":{"Desktop":{"type":"variable","id":"theme-3"}},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"prefix":"","number":"20","suffix":"","title":"Years of Experience","showSupper":true,"superColor":{"type":"variable","id":"theme-1"},"superTypography":{"type":"variable","id":"gVRepE","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"superTop":{"Desktop":"9"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"r":37,"g":36,"b":37,"a":1}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":"0"},"numberRightSpace":{"Desktop":"0"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-QFmYhS guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-badge"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="20" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Years of Experience</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-fwxGiC","margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fwxGiC"><div class="guten-column-wrapper" data-id="fwxGiC"><!-- wp:gutenverse/fun-fact {"elementId":"guten-gk6tTa","icon":"gtn gtn-team-2-line","iconColor":{"Desktop":{"type":"variable","id":"theme-3"}},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"prefix":"","number":"52","suffix":"","title":"Expert Carpenter","showSupper":true,"superColor":{"type":"variable","id":"theme-1"},"superTypography":{"type":"variable","id":"gVRepE","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"superTop":{"Desktop":"9"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"r":37,"g":36,"b":37,"a":1}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"nMGsuT","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"titleTypography":{"type":"variable","id":"k2MSOO","font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"transform":"normal","size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":"0"},"numberRightSpace":{"Desktop":"0"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-gk6tTa guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-2-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="52" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Expert Carpenter</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"roof-construction.webp","image_url":"https:\/\/designer.gutenverse.com\/woodzone\/wp-content\/uploads\/sites\/89\/2024\/11\/roof-construction.webp","type":"sync","id":1303}]',
	'is_sync' => true,
);
